cards/urls.py
from django.conf.urls import patterns, url, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'cards', views.CardRESTView, base_name='cards-api')
router.register(r'sets', views.CardSetRESTView, base_name='sets-api')
#router.register(r'types', views.TypeRESTView, base_name='types-api')

urlpatterns = [
    # ex: /cards/search/
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    # ex: /cards/id/{id}/
    url(r'^(?P<pk>[0-9]+)$', views.CardView.as_view(), name='card'),
    # Django Rest Framework URLs
    url(r'^api/', include(router.urls)),
    url(r'^api/types', views.TypeRESTView.as_view(), name='types')
]

mtg/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from django.shortcuts import redirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^cards/', include('cards.urls' , namespace='cards')),
    #url(r'^'      , include(urls)),
    #url(r'^'      , include('accounts.urls', namespace='accounts')),
    #url(r'^login/', views.login, name="login"),
    #url(r'^login/' , include('login.urls' , namespace="login")),
    #url(r'^logout/', include('logout.urls', namespace="logout")),
    url(r'^admin/' , include(admin.site.urls)),
    # redirect to /cards/search/
    url(r'^', RedirectView.as_view(pattern_name='cards:search'))
    #url(r'^', redirect(reverse_lazy('cards:search')))
]

cards/models/booster.py
from django.db import models
from .card_set import CardSet

class Booster(models.Model):
    card_set = models.ForeignKey(CardSet)

class BoosterSlot(models.Model):
    booster = models.ForeignKey(Booster)
    # Common types:
    #    common
    #    uncommon
    #    rare
    #    mythic rare
    #    land
    #    marketing
    #    checklist
    #    double faced
    # Time spiral:
    #    timeshifted common
    #    timeshifted uncommon
    #    timeshifted rare
    #    timeshifted purple
    # Conspiracy:
    #    draft-matters
    # Vintage Masters:
    #    power nine
    #    foil
    # Modern Masters:
    #    foil common
    #    foil uncommon
    #    foil rare
    #    foil mythic rare
    # Cards marked as "starter: true" should be exempted from booster generation
    booster_slot = models.CharField(max_length=32, default="")

cards/models/card.py
from django.db import models
from .color import Color

class Card(models.Model):
    LAYOUT_CHOICES = (
        ('normal'      , 'Normal'),
        ('split'       , 'Split'),
        ('flip'        , 'Flip'),
        ('double-faced', 'Double-faced'),
        ('token'       , 'Token'),
        ('plane'       , 'Plane'),
        ('scheme'      , 'Scheme'),
        ('phenomenon'  , 'Phenomenon'),
        ('leveler'     , 'Leveler'),
        ('vanguard'    , 'Vanguard'),
    )
    layout = models.CharField(max_length=40,
                              choices=LAYOUT_CHOICES, 
                              default='normal')

    name = models.CharField(max_length=150, default="")

    mana_cost = models.CharField(max_length=64, default=0)
    cmc = models.PositiveIntegerField(verbose_name="CMC", default=0)
    colors = Color()
    color_identity = Color()
   
    type_text = models.CharField(max_length=255, default="")

    # Current longest oracle text is 544 characters
    text = models.CharField(max_length=1024, default="", blank=True)

    # Sometimes power and toughness can be *
    power = models.CharField(max_length=8, default="", blank=True)
    toughness = models.CharField(max_length=8, default="", blank=True)
    
    # Only set for Planeswalkers
    loyalty = models.PositiveSmallIntegerField(default=0, blank=True)

    # Only set for Vanguard cards
    hand = models.SmallIntegerField(default=0, blank=True)
    life = models.SmallIntegerField(default=0, blank=True)

    # True if on the reserved list (cannot be reprinted)
    reserved = models.BooleanField(default=False)

    class Meta:
        ordering = ['-pk']

    def get_absolute_url(self):
        return "/cards/%i" % self.id

    def __str__(self):
        return self.name

cards/models/card_set.py
from django.db import models
from . import const

class CardSet(models.Model):
    name          = models.CharField(max_length=64, default="", unique=True)
    
    code          = models.CharField(max_length=8, primary_key=True)
    gatherer_code = models.CharField(max_length=8, default="")
    old_code      = models.CharField(max_length=8, default="")
    magic_cards_info_code = models.CharField(max_length=8, default="")
    
    release_date = models.DateField()
    border = models.CharField(max_length=6, 
                              choices=const.BORDER_CHOICES,
                              default='black')
    SET_TYPE_CHOICES = (
       ('core'          , 'Core'          ),
       ('expansion'     , 'Expansion'     ),
       ('reprint'       , 'Reprint'       ),
       ('box'           , 'Box'           ),
       ('un'            , 'Un'            ),
       ('from the vault', 'From the Vault'),
       ('premium deck'  , 'Premium Deck'  ),
       ('duel deck'     , 'Duel Deck'     ),
       ('starter'       , 'Starter'       ),
       ('commander'     , 'Commander'     ),
       ('planechase'    , 'Planechase'    ),
       ('archenemy'     , 'Archenemy'     ),
       ('promo'         , 'Promo'         ),
       ('vanguard'      , 'Vanguard'      ),
       ('masters'       , 'Masters'       ),
    )
    set_type = models.CharField(max_length=16,
                                choices   =SET_TYPE_CHOICES,
                                default   ='expansion')
    block       = models.CharField(max_length=32, default="")
    online_only = models.BooleanField(default=False)

    def __str__(self):
         return self.name

cards/models/color.py
from django.db import models

class Color(models.fields.PositiveSmallIntegerField):
    description = "The color of a Magic card"

    choices_dict = {
        'Colorless': 0,
        'White'    : 1,
        'Blue'     : 2,
        'Black'    : 4,
        'Red'      : 8,
        'Green'    :16,
    }
    
    choices_id_dict = {
        'Colorless': 0,
        'White'    : 1,
        'W'        : 1,
        'Blue'     : 2,
        'U'        : 2,
        'Black'    : 4,
        'B'        : 4,
        'Red'      : 8,
        'R'        : 8,
        'Green'    :16,
        'G'        :16,
    }

    choices_form = (
        ('Colorless', 'Colorless'),
        ('White'    , 'White'    ),
        ('Blue'     , 'Blue'     ),
        ('Black'    , 'Black'    ),
        ('Red'      , 'Red'      ),
        ('Green'    , 'Green'    ),
    )

    # Take ['White', 'Red'] and convert to 01001 binary (9 in base 10)
    # Also assuming Big Endianess but that shouldn't be super relevant
    def get_prep_value(self, value):
        bitmask = 0
        if value != None:
            for color in value:
               bitmask += self.choices_id_dict[color]
        return bitmask

    # Take 01101 binary and convert to ['Blue', 'Black', 'Green']
    def to_python(self, value):
        return value

    def from_db_value(self, value, expression, connection, context):
        colors = []
        if value == 0: colors = ['Colorless']
        else:
            for choice in self.choices_dict:
                if (self.choices_dict[choice] & value): #Then it is that color
                    colors.append(choice)
        return colors

    def formfield(self, **kwargs):
        from cards.forms import ColorForm
        return ColorForm(
            choices = self.choices_form,
        )

cards/models/const.py
BORDER_CHOICES = (
    ('black' , 'Black' ),
    ('white' , 'White' ),
    ('silver', 'Silver'),
    ('gold'  , 'Gold'  ),
)

cards/models/details.py
from django.db import models
from .card import Card
from .card_set import CardSet
from .printed_card import PrintedCard

class Legalities(models.Model):
    card = models.ForeignKey(Card)
    game_format = models.CharField(max_length=64, default="")
    LEGALITY_CHOICES = (
        ('L', 'Legal'),
        ('R', 'Restricted'),
        ('B', 'Banned'),
    )
    legality = models.CharField(max_length=16, default="")

class Rulings(models.Model): 
    card = models.ForeignKey(Card)
    date = models.DateField()
    text = models.CharField(max_length=2047, default="")

class Printings(models.Model):
    card     = models.ForeignKey(Card)
    set_code = models.ForeignKey(CardSet)

class CardNames(models.Model):
    card = models.ForeignKey(Card)
    name = models.CharField(max_length=255, default="")

class ForeignNames(models.Model):
    card = models.ForeignKey(PrintedCard)
    LANGUAGE_CHOICES = (
        ('Standard', (
            ('en'     , 'English'),
            ('zh-HANT', 'Chinese Traditional'),
            ('de'     , 'German'),
            ('fr'     , 'French'),
            ('it'     , 'Italian'),
            ('ja'     , 'Japanese'),
            ('ko'     , 'Korean'),
            ('pt-BR'  , 'Portuguese (Brazil)'),
            ('ru'     , 'Russian'),
            ('zh-HANS', 'Chinese Simplified'),
            ('es'     , 'Spanish'),
            )
        ),
        ('Promo', (
            ('he'      , 'Hebrew'),
            ('cyrillic', 'Cyrillic'),
            ('grc'     , 'Classic Greek'),
            )
        )
    )
    language      = models.CharField(max_length=32,
                                     choices=LANGUAGE_CHOICES,
                                     default='en')
    name          = models.CharField(max_length=255, default="")
    multiverse_id = models.PositiveIntegerField(default=0)

class Variations(models.Model):
    card = models.ForeignKey(PrintedCard)
    multiverse_id = models.PositiveIntegerField(default=0)

cards/models/printed_card.py
from django.db import models
from .card import Card
from .card_set import CardSet
from . import const

class PrintedCard(models.Model):
    card = models.ForeignKey(Card)
    card_set = models.ForeignKey(CardSet)
    card_id_hash  = models.CharField(max_length=40  , default="", unique=True)
    original_text = models.CharField(max_length=1024, default="", blank=True)
    original_type = models.CharField(max_length=255 , default="", blank=True)
    flavor        = models.CharField(max_length=1024, default="", blank=True)
    RARITY_CHOICES = (
        ('M'  , 'Mythic Rare'),
        ('R'  , 'Rare'       ),
        ('U'  , 'Uncommon'   ),
        ('C'  , 'Common'     ),
        ('L'  , 'Land'       ),
        ('S'  , 'Special'    ),
        ('P'  , 'Promo'      ),
        ('B'  , 'Bonus'      ),
    )
    rarity = models.CharField(max_length=12, choices=RARITY_CHOICES, default="")
    artist = models.CharField(max_length=64, default="")
    number = models.CharField(max_length=8 , default="", blank=True)
    multiverse_id = models.PositiveIntegerField(default=0)
    image_name    = models.CharField(max_length=255, default="")
    watermark     = models.CharField(max_length=64, default="")
    border = models.CharField(max_length=6, 
                              choices=const.BORDER_CHOICES, 
                              default='black')
    # Set to true if a timeshifted card (only for the Time Spiral set)
    timeshifted  = models.BooleanField(default=False)
    # Release date cannot be a DateTime field
    # because sometimes only the month is given
    release_date      = models.DateField(blank=True, null=True)
    release_date_text = models.CharField(max_length=10, default="", blank=True)
    # Set to true if released as part of a core set box (not in boosters)
    starter = models.BooleanField(default=False)
    # Where the card was originally obtained if it was a promo card
    source  = models.CharField(max_length=255, default="", blank=True)

    def img_url(self):
        return "%s/%s.jpg" % (self.card_set.pk, self.image_name)

    class Meta:
        ordering = ['-release_date', 'card_set__code', 'image_name']

    def __str__(self):
        return self.card_set.name

cards/models/types.py
from django.db import models
from .card import Card

class Supertypes(models.Model):
    card = models.ForeignKey(Card)
    SUPERTYPE_CHOICES = ( 
        ('Basic'    , 'Basic'    ),
        ('Legendary', 'Legendary'),
        ('Ongoing'  , 'Ongoing'  ),
        ('Snow'     , 'Snow'     ),
        ('World'    , 'World'    ),
    )
    supertype_name = models.CharField(max_length=12,
                                      choices=SUPERTYPE_CHOICES,
                                      default="")
    def __str__(self):
        return self.supertype_name

class Types(models.Model):
    card = models.ForeignKey(Card)
    TYPE_CHOICES = (
        ('Base', (
            ('Artifact'    , 'Artifact'    ),
            ('Creature'    , 'Creature'    ),
            ('Emblem'      , 'Emblem'      ),
            ('Enchantment' , 'Enchantment' ),
            ('Instant'     , 'Instant'     ),
            ('Land'        , 'Land'        ),
            ('Planeswalker', 'Planeswalker'),
            ('Tribal'      , 'Tribal'      ),
            ('Sorcery'     , 'Sorcery'     ),
            )
        ),
        ('Other', (
            ('Conspiracy', 'Conspiracy'),
            ('Phenomenon', 'Phenomenon'),
            ('Plane'     , 'Plane'     ),
            ('Scheme'    , 'Scheme'    ),
            ('Vanguard'  , 'Vanguard'  ),
            )
        )
    )
    type_name = models.CharField(max_length=12,
                                 choices=TYPE_CHOICES,
                                 default="")
    def __str__(self):
        return self.type_name

class Subtypes(models.Model):
    card = models.ForeignKey(Card)
    subtype_name = models.CharField(max_length=31)
    def __str__(self):
        return self.subtype_name

cards/forms/color_form.py
from django import forms
from django.utils.safestring import mark_safe

class ColorForm(forms.MultipleChoiceField):
    widget = forms.CheckboxSelectMultiple

cards/views.py
from django.shortcuts import render
from django.views import generic

from haystack.generic_views import SearchView
from rest_framework import generics, views, viewsets, pagination
from rest_framework import response, status, serializers
from rest_framework import authentication, permissions, filters
from drf_haystack.viewsets import HaystackViewSet
from drf_haystack.filters import HaystackAutocompleteFilter

from .models import Card, CardSet, Types
from .serializers import CardSearchSerializer, CardSetSerializer

class SearchView(SearchView):
    template_name = 'search/search.html'

class CardView(generic.DetailView):
    model = Card
    template_name = 'cards/card.html'

class CardRESTView(HaystackViewSet):
    index_models = [Card]
    serializer_class = CardSearchSerializer
    filter_backends = [HaystackAutocompleteFilter, filters.OrderingFilter]
    load_all = True

class AllResultsSetPagination(pagination.PageNumberPagination):
    page_size = 1000
    page_size_query_param = 'page_size'
    max_page_size = 0

class CardSetRESTView(viewsets.ModelViewSet):
    queryset = CardSet.objects.all().order_by('-release_date')
    serializer_class = CardSetSerializer
    pagination_class = AllResultsSetPagination

class TypeRESTView(views.APIView):
    def get(self, request, format=None):
        types = [value[0] for value in sum([category[1] for category in Types.TYPE_CHOICES], ())]
        return response.Response(types)

cards/templates/cards/base.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta id="meta" name="viewport" content="width=device-width; initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'cards/styles/oswald-font.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'cards/styles/angular-material.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'cards/styles/main.css' %}" />
    {% block styles %}{% endblock %}

    <script type="text/javascript" src="{% static 'cards/scripts/ng/angular.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'cards/scripts/ng/angular-animate.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'cards/scripts/ng/angular-aria.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'cards/scripts/ng/angular-messages.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'cards/scripts/ng/angular-material.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'cards/scripts/ng/angular-resource.js' %}"></script>
    <script type="text/javascript" src="{% static 'cards/scripts/ng/angular-ui-router.min.js' %}"></script>

    {% block scripts %}{% endblock %}
</head>
<body ng-app="cards" ng-controller="search">
    <header>
        {% block menubutton %}{% endblock %}
        <h1>MTG Cards</h1>
        <nav>
            {% comment %}
            <ul>
                <li><a href="/cards/search">Card Search</a></li><li><a href="/collection">Collection</a></li><li><a href="#">Decks</a></li><li><a href="#">Login</a></li>
            </ul>
            {% endcomment %}
        </nav>
    </header>
    <main>
{% block content %}{% endblock %}
    </main>
    <footer>
        Magic: The Gathering and related images are owned by Wizards of the Coast. This website is unaffiliated with Wizards of the Coast.
    </footer>
</body>

cards/templates/cards/card.html
{% extends 'cards/base.html' %}

{% load staticfiles %}

{% load debug %}
{% load card_extras %}

{% block content %}
<md-content class="card-result">
    {% comment %}
    <div class="card-nav">
        <ul>
            <li><a href="#printings">Printings</a></li>
            <li><a href="#rulings-and-legal">Rulings &amp; Legalities</a></li>
            <li><a href="#languages">Languages</a></li>
        </ul>
    </div>
    {% endcomment %}
    <div class="card">
        <div class="card-image">
    	    {% with card.printedcard_set.first as pc %}
    	    <img src="{% static "" %}images/cards/{{pc.card_set.code}}/{{pc.image_name}}.jpg" alt="{{ card.name }}" width="{% if card.layout = "plane" or card.layout == "phenomenon" %}445px{% else %}312px{% endif %}" />
    	    {% endwith %}
        </div>
        <div class="card-info">
            <span class="mana-cost">
                {{ card.mana_cost|mana_cost_to_img }}<br />
                <abbr title="Converted Mana Cost">CMC</abbr> {{ card.cmc }}
            </span>
            <h2>{% block title %}{{ card.name }}{% endblock %}</h2>
            <p class="type">{{ card.type_text }}</p>
            <p class="rules-text">{{ card.text|rules_text_to_html }}</p>
            <ul>
                {% if card.power %}
                <li><abbr title="Power">P</abbr> / <abbr title="Toughness">T</abbr>: {{ card.power }} / {{ card.toughness }}</li>
                {% endif %}
            </ul>
        </div>
    </div>
    <h3><a name="printings">Printings</a></h3>
    <div class="printings">
        <div>
        {% for pc in card.printedcard_set.all %}
            <div>
                <div>{{pc.card_set.name}}</div>
    	    <img src="{% static "" %}images/cards/{{pc.card_set.code}}/{{pc.image_name}}.jpg" alt="{{card.name}} ({{pc.card_set.name}})" width="{% if card.layout == "plane" or card.layout == "phenomenon" %}445px{% else %}312px{% endif %}" />
            </div>
        {% endfor %}
        </div>
    </div>
</md-content>
{% endblock %}